name: Deploy political-persecutions-web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Prepare Prisma Client
        run: npx prisma generate
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t aleksandrivanov22/political-persecutions-web .
      - name: Publish image to docker hub
        run: docker push aleksandrivanov22/political-persecutions-web:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull aleksandrivanov22/political-persecutions-web:latest
      - name: Delete old container
        run: docker rm -f political-persecutions-web
      - name: Run docker container
        run: docker run -d -p 3000:3000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} --name political-persecutions-web aleksandrivanov22/political-persecutions-web